### PR TITLE
Bugfix/preflight headers and store multiple cookies

### LINKED ISSUE #70: Request fails during preflight (OPTIONS) when informed custom headers and method 'DELETE'
**Describe the bug**
When the client performs a preflight request (HTTP/ OPTIONS), the tshield sends back the headers 'Access-Control-Allow-Headers' and 'Access-Control-Allow-Methods', that results in error of 'Cross-Origin Resource Sharing (CORS)', once ther first restrict the possibile allowed headers in: Authorization, Content-Type, Accept, X-User-Email, X-Auth-Token; and the second does not inform the allowed methods supported. 

**To Reproduce**
Perform a preflight request (HTTP/ OPTIONS), for a DELETE endpoint, that sends a header not supported.

**Expected behavior**
Allow the preflight request return status OK (200)

### LINKED ISSUE #71: Unable to restore stubs with multiple 'set-cookie' headers values
**Describe the bug**
When the end service returns multiple 'set-cookie' headers, the tshiled is able to save them, however, when they're restored and sent to back, the browser recognizes as a unique cookie.

**To Reproduce**
Perform a stub record/ save from a endpoint that returns multiple 'set-cookie' headers.

**Expected behavior**
Restore and send back from stub all the cookies  sent by original service.

### PR DESCRIPTION
**Pull request by wfercosta**
## Description

Fixes restrictions on 'Access-Control-Allow-Headers' and 'Access-Control-Allow-Methods', due the preflight behavior. 

Fixes #70
Fixes #71 

## Type of change

Please delete options that are not relevant.

*   [x] Bug fix

### CODE REVIEW

File: lib/tshield/request_vcr.rb [hunk 1]
```diff
@@ -80,10 +80,20 @@ def method
...
       end
 
+      field = raw_response.get_fields('Set-Cookie')
+
+      if !field.nil? && !field.empty?
+        cookies_values = []
+        field.each { |value| cookies_values.push(value) }
+        headers['Set-Cookie'] = cookies_values
+      end
+
```
Comment (diegorubin) [inline lib/tshield/request_vcr.rb:96]: Can you extract the new logic to a new method please?
Removing code from here I think this issue can be solved.
https://app.sourcelevel.io/github/diegorubin/-/tshield/reviews/119/file/lib/tshield/request_vcr.rb#L81

**Review by diegorubin — CHANGES_REQUESTED** [review]
Wander, could you create unit or component tests to cover this changes?

The TShield has many coverage issues and we trying to cover all new changes.

I saw that the coverall validation was not executed in your pull request. I fixed this in the master branch. Can you update the branch please?

File: lib/tshield/request_vcr.rb (hunk 1 above)
Comment (wfercosta) [reply lib/tshield/request_vcr.rb]: Hi Rubin, can u review the updates?

**Review by guilhermerbueno — APPROVED** [review]

**Review by diegorubin — APPROVED** [review]
